# Generated by Django 6.0.1 on 2026-01-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_orderitem'),
        ('products', '0009_productcolor_productsize_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_file',
            field=models.FileField(blank=True, help_text='Custom file uploaded by customer', null=True, upload_to='orders/files/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
    ]
