# Generated by Django 6.0.1 on 2026-02-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitem_unique_together_cartitem_variant_and_more'),
        ('products', '0025_rename_products_pr_product_idx_products_pr_product_b400cb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
    ]
