# Generated by Django 6.0.1 on 2026-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_orders/'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
