# Generated by Django 6.0.1 on 2026-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartitem_unique_together_cartitem_custom_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_customizations/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
