# Generated by Django 6.0.1 on 2026-03-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cartitemimage_orderitemimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id']},
        ),
    ]
