# Generated by Django 5.2.10 on 2026-04-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_product_snapshot_and_soft_reference'),
        ('products', '0028_alter_category_id_alter_color_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
    ]
