# Generated by Django 6.0.1 on 2026-01-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
