# Generated by Django 6.0.1 on 2026-01-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcolor_productsize_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_type',
            field=models.CharField(choices=[('main', 'Main Stock'), ('variants', 'Variant Stock')], default='main', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text="Only used if stock_type is 'main'"),
        ),
    ]
