# Generated by Django 6.0.1 on 2026-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productvariant_color_alter_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_custom_image',
            field=models.BooleanField(default=False, help_text='Allow customers to upload custom images'),
        ),
    ]
