# Generated by Django 6.0.1 on 2026-01-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_allow_custom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_custom_text',
            field=models.BooleanField(default=False, help_text='Allow customers to add custom text'),
        ),
    ]
