# Generated by Django 6.0.1 on 2026-01-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_size_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product price', max_digits=10, null=True),
        ),
    ]
