# Generated by Django 6.0.1 on 2026-02-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_options_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Discount percentage (auto-calculated)', null=True),
        ),
    ]
