# Generated by Django 6.0.1 on 2026-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productvariant_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_image_limit',
            field=models.PositiveIntegerField(default=1, help_text='Number of images customer can upload (only if custom image is allowed)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
