# Generated by Django 6.0.1 on 2026-02-03 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_custom_image_limit_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_image_limit',
            field=models.PositiveIntegerField(default=1, help_text='Number of images customer can upload (only if custom image is allowed)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
