# Generated by Django 6.0.1 on 2026-02-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productactivity',
            new_name='products_pr_product_b400cb_idx',
            old_name='products_pr_product_idx',
        ),
    ]
