# Generated by Django 5.2.10 on 2026-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_stock_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Set when the product is archived', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hidden_from_storefront',
            field=models.BooleanField(default=False, help_text='Fully hide this product from the storefront (detail page returns 404). Only relevant for archived products.'),
        ),
    ]
