"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _product_card from './product-card.bones.json'
import _category_card from './category-card.bones.json'

configureBoneyard({"color":"#E7E5E4","darkColor":"#292524","animate":"shimmer","shimmerColor":"#FAFAF9","darkShimmerColor":"#44403C","speed":"1.8s","shimmerAngle":110})

registerBones({
  "product-card": _product_card,
  "category-card": _category_card,
})
